routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('marketplace');
});

Auth::routes();

Route::get('/auth/{name}', 'SocialAuthController@redirectToProvider');
Route::get('/auth/{name}/callback', 'SocialAuthController@handleProviderCallback');

Route::middleware([\App\Http\Middleware\Authenticate::class])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('products', 'ProductController');
});

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Providers\RouteServiceProvider;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;
use App\Entity\Product;

class ProductController extends Controller
{
    private $repository;
    private $redirectTo = RouteServiceProvider::HOME;

    public function __construct(Product $product)
    {
        $this->repository = $product;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->repository->paginate(6);

        return view('product.list', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $product = $this->repository->newInstance();

        if (Gate::denies('create', $product)) {
            Session::flash('warning_msg', 'You don\'t have rights to create products!');
            return redirect($this->redirectTo);
        }

        $url = route('products.store');

        return view('product.create', compact('product', 'url'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request)
    {
        if (Gate::denies('create', $this->repository)) {
            Session::flash('warning_msg', 'You don\'t have rights to create products!');
            return redirect($this->redirectTo);
        }

        $product = $this->repository->newInstance();
        $product->user_id = Auth::id();
        $product->name = $request->input('name');
        $product->price = $request->input('price');
        $result = $product->save();

        if ($result) {
            Session::flash('success_msg', "Product {$product->name} has been successfully created!");
        } else {
            Session::flash('error_msg', 'Some error happens try again later!');
        }

        return redirect()->route('products.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = $this->repository->find($id);

        if (Gate::denies('view', $product)) {
            Session::flash('warning_msg', 'You don\'t have rights to edit this product!');
            return redirect($this->redirectTo);
        }

        return view('product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = $this->repository->find($id);

        if (Gate::denies('update', $product)) {
            Session::flash('warning_msg', 'You don\'t have rights to edit this product!');
            return redirect($this->redirectTo);
        }

        $url = route('products.update', $product->id);

        return view('product.edit', compact('product', 'url'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, $id)
    {
        $product = $this->repository->find($id);

        if (Gate::denies('update', $product)) {
            Session::flash('warning_msg', 'You don\'t have rights to edit this product!');
            return redirect($this->redirectTo);
        }

        $product->name = $request->input('name');
        $product->price = $request->input('price');

        $result = $product->save();
        if ($result) {
            Session::flash('success_msg', "Product {$product->name} has been updated!");
        } else {
            Session::flash('error_msg', 'Some error happens try again later!');
        }

        return redirect()->route('products.view', ['id' => $product->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = $this->repository->find($id);

        if (Gate::denies('delete', $product)) {
            Session::flash('warning_msg', 'You don\'t have rights to delete this product!');
            return redirect($this->redirectTo);
        }

        $result = $product->delete();

        if ($result) {
            Session::flash('success_msg', "Product {$product->name} successfully deleted!");
        } else {
            Session::flash('error_msg', 'Some error happens try again later!');
        }

        return redirect()->route('products.index');
    }
}

app/Http/Controllers/SocialAuthController.php
<?php

namespace App\Http\Controllers;

use App\Entity\User;
use App\Providers\RouteServiceProvider;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Laravel\Socialite\Facades\Socialite;
use Illuminate\Support\Facades\Session;

class SocialAuthController extends Controller
{
    protected $redirectPath = RouteServiceProvider::HOME;

    public function redirectToProvider($provider)
    {
        return Socialite::driver($provider)->redirect();
    }

    public function handleProviderCallback($provider)
    {
        try {

            $socialUser = Socialite::driver($provider)->user();

            $user = User::where(['email' => $socialUser->email])->first();

            if (!$user) {
                $user = User::create([
                    'name' => $socialUser->name,
                    'email' => $socialUser->email,
                    'password' => Hash::make('password'), //Just for demo password
                ]);
            }

            Auth::login($user);

            return redirect($this->redirectPath);
        } catch (\Exception $e) {
            Session::flash('error_msg', $e->getMessage());
            return redirect('/');
        }
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdownProducts" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                Products <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('products.index') }}">
                                    {{ __('List') }}
                                </a>
                                @can('create', App\Entity\Product::class)
                                    <a class="dropdown-item" href="{{ route('products.create') }}">
                                        {{ __('Add') }}
                                    </a>
                                @endcan
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>

                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @if(Session::has('success_msg'))
                        <div class="alert alert-success" role="alert">
                            {{ Session::get('success_msg') }}
                        </div>
                    @endif
                    @if(Session::has('warning_msg'))
                        <div class="alert alert-warning" role="alert">
                            {{ Session::get('warning_msg') }}
                        </div>
                    @endif
                    @if(Session::has('error_msg'))
                        <div class="alert alert-danger" role="alert">
                            {{ Session::get('error_msg') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-8 text-right">
                    @include('product.actions.buttons.add')
                </div>
            </div>
        </div>
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/marketplace.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 class="bd-title" id="content">Marketplace</h1>
                <h6>Powered by <span>Laravel</span></h6>
            </div>
        </div>
    </div>
@endsection

resources/views/product/_form.blade.php
<form action="{{ $url }}" method="post">
    @csrf
    @if($product->exists)
        {{ method_field('PUT') }}
    @endif

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name="name" value="{{old('name', $product->name)}}">
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <input type="text" class="form-control" id="price" name="price" value="{{old('price', $product->price)}}">
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>

resources/views/product/actions/buttons/add.blade.php
@can('create', App\Entity\Product::class)
    <a href="{{route('products.create')}}" class="btn btn-success">Add new product</a>
@endcan

resources/views/product/actions/buttons/delete.blade.php
@can('delete', $product)
    <form
            action="{{ route('products.destroy', $product->id) }}"
            method="POST"
            style="display: inline-block"
    >
        @csrf
        {{ method_field('DELETE') }}
        <button class="btn btn-danger">Delete</button>
    </form>
@endcan

resources/views/product/actions/buttons/edit.blade.php
@can('update', $product)
    <a href="{{route('products.edit', $product->id)}}" class="btn btn-info">Edit</a>
@endcan

resources/views/product/actions/buttons/view.blade.php
@can('view', $product)
    <a href="{{route('products.show', $product->id)}}" class="btn btn-success">View</a>
@endcan

resources/views/product/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <h2>Create new product</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-4">
                @include('product._form')
            </div>
        </div>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4">
                <h2>Edit product {{ $product->name }}</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-4">
                @include('product._form')
            </div>
        </div>
    </div>
@endsection

resources/views/product/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if ($products)
                    <table class="table table-striped">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Price</th>
                            <th scope="col"></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($products as $product)
                            <tr>
                                <th scope="row">
                                    <a href="{{route('products.show', $product->id)}}">
                                        {{ $product->name }}
                                    </a>
                                </th>
                                <td>$ {{ $product->price }}</td>
                                <th class="text-right">
                                    @include('product.actions.buttons.view')
                                    @include('product.actions.buttons.edit')
                                    @include('product.actions.buttons.delete')
                                </th>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <?php echo $products->render(); ?>
                @else
                    <div class="card">
                        <div class="card-body">
                            There are no products!
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

resources/views/product/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">{{ $product->name }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">$ {{ $product->price }}</h6>
                        @include('product.actions.buttons.edit')
                        @include('product.actions.buttons.delete')
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection